### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by miriammalka** [miriammalka/memorygame#3]

**Comment by AshiraFriedman** [comment]
I did QA, looks very good, great job!
Please fix the bug that I opened an issue for, and if all is good, we can start the code review

**Comment by AshiraFriedman** [comment]
Amazing work!
I will start a code review now and will give you feedback when I'm done.

**Comment by AshiraFriedman** [comment]
Wow! Really nice, clear and concise code.  Well done!
Please see just a few comments on minor fixes and resubmit.

**Comment by AshiraFriedman** [comment]
Super job!
Code review is done, all looks good.
I also did the second round of QA and the game is working well, didn't notice any bugs:)
Just one fix but no need to resubmit for this - it's confusing because the form is named form1 but then the form class is called frmMemory so the form should also be called that.  Please fix that.

**Comment by miriammalka** [comment]
ok, I made that change. Thank you so much for your help!

**Comment by AshiraFriedman** [comment]
Great! My pleasure!
